---
title: "DASC 1104 Project Proposal"
author: "Hayden McDonald"
date: "12/3/2020"
output: pdf_document
---

<link href="/rmarkdown-libs/anchor-sections/anchor-sections.css" rel="stylesheet" />
<script src="/rmarkdown-libs/anchor-sections/anchor-sections.js"></script>


<div id="my-blog-link" class="section level1">
<h1>My Blog Link</h1>
<p>My blog is available at <a href="https://hpmcdona.netlify.app/">https://hpmcdona.netlify.app/</a></p>
<pre class="r"><code>library(here)
library(ggplot2)
library(tidyverse)
library(readxl)
knitr::opts_chunk$set(echo = FALSE, tidy = TRUE)
spotify &lt;- read_csv(here::here(&quot;data&quot;, &quot;tidytuesday&quot;,
                               &quot;data&quot;,&quot;2020&quot;,&quot;2020-01-21&quot;,&quot;spotify_songs.csv&quot;))</code></pre>
<p>Exploring the Spotify data.</p>
<pre><code>## Observations: 32,833
## Variables: 23
## $ track_id                 &lt;chr&gt; &quot;6f807x0ima9a1j3VPbc7VN&quot;, &quot;0r7CVbZTWZgbTCYdf…
## $ track_name               &lt;chr&gt; &quot;I Don&#39;t Care (with Justin Bieber) - Loud Lu…
## $ track_artist             &lt;chr&gt; &quot;Ed Sheeran&quot;, &quot;Maroon 5&quot;, &quot;Zara Larsson&quot;, &quot;T…
## $ track_popularity         &lt;dbl&gt; 66, 67, 70, 60, 69, 67, 62, 69, 68, 67, 58, …
## $ track_album_id           &lt;chr&gt; &quot;2oCs0DGTsRO98Gh5ZSl2Cx&quot;, &quot;63rPSO264uRjW1X5E…
## $ track_album_name         &lt;chr&gt; &quot;I Don&#39;t Care (with Justin Bieber) [Loud Lux…
## $ track_album_release_date &lt;chr&gt; &quot;2019-06-14&quot;, &quot;2019-12-13&quot;, &quot;2019-07-05&quot;, &quot;2…
## $ playlist_name            &lt;chr&gt; &quot;Pop Remix&quot;, &quot;Pop Remix&quot;, &quot;Pop Remix&quot;, &quot;Pop …
## $ playlist_id              &lt;chr&gt; &quot;37i9dQZF1DXcZDD7cfEKhW&quot;, &quot;37i9dQZF1DXcZDD7c…
## $ playlist_genre           &lt;chr&gt; &quot;pop&quot;, &quot;pop&quot;, &quot;pop&quot;, &quot;pop&quot;, &quot;pop&quot;, &quot;pop&quot;, &quot;p…
## $ playlist_subgenre        &lt;chr&gt; &quot;dance pop&quot;, &quot;dance pop&quot;, &quot;dance pop&quot;, &quot;danc…
## $ danceability             &lt;dbl&gt; 0.748, 0.726, 0.675, 0.718, 0.650, 0.675, 0.…
## $ energy                   &lt;dbl&gt; 0.916, 0.815, 0.931, 0.930, 0.833, 0.919, 0.…
## $ key                      &lt;dbl&gt; 6, 11, 1, 7, 1, 8, 5, 4, 8, 2, 6, 8, 1, 5, 5…
## $ loudness                 &lt;dbl&gt; -2.634, -4.969, -3.432, -3.778, -4.672, -5.3…
## $ mode                     &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,…
## $ speechiness              &lt;dbl&gt; 0.0583, 0.0373, 0.0742, 0.1020, 0.0359, 0.12…
## $ acousticness             &lt;dbl&gt; 0.10200, 0.07240, 0.07940, 0.02870, 0.08030,…
## $ instrumentalness         &lt;dbl&gt; 0.00e+00, 4.21e-03, 2.33e-05, 9.43e-06, 0.00…
## $ liveness                 &lt;dbl&gt; 0.0653, 0.3570, 0.1100, 0.2040, 0.0833, 0.14…
## $ valence                  &lt;dbl&gt; 0.518, 0.693, 0.613, 0.277, 0.725, 0.585, 0.…
## $ tempo                    &lt;dbl&gt; 122.036, 99.972, 124.008, 121.956, 123.976, …
## $ duration_ms              &lt;dbl&gt; 194754, 162600, 176616, 169093, 189052, 1630…</code></pre>
</div>
<div id="spotify" class="section level1">
<h1>Spotify</h1>
<p>For this project I am examining the Spotify Songs dataset contained in the spotify_songs.csv
file on the Tidy Tuesday website. The data consists of 23 variables with 32,833 observations, the definitions for each variable were taken directly from the <a href="https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-21/readme.md">Tidy Tuesday Spotify website</a>. The variables track_id(song unique ID), track_name(song name), track_artist(song artist), track_album_id(album unique ID), track_album_name(song album name), track_album_release_date(date when album released), playlist_name(name of playlist), playlist_id(unique playlist ID for each playlist), playlist_genre(playlist genre), and playlist_subgenre(playlist subgenre) are all characters. The variable track_popularity(song popularity, 0-100) where higher is better is a double. The variable danceability is a double that describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable. The variable energy is a double that measures from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy. The variable key is a double where Integers map to pitches using standard Pitch Class notation . E.g. 0 = C, 1 = Csharp/Dflat, 2 = D, and so on. If no key was detected, the value is -1. The variable loudness is a double that measures the overall loudness of a track in decibels (dB). Loudness values are averaged across the entire track and are useful for comparing relative loudness of tracks. Loudness is the quality of a sound that is the primary psychological correlate of physical strength (amplitude). Values typical range between -60 and 0 db. The variable mode is a double that indicates the modality (major or minor) of a track, the type of scale from which its melodic content is derived. Major is represented by 1 and minor is 0. The variable speechiness is a double that detects the presence of spoken words in a track. The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks. The variable acousticness is a double is a confidence measure from 0.0 to 1.0 of whether the track is acoustic. 1.0 represents high confidence the track is acoustic. The variable instrumentalness is a double that predicts whether a track contains no vocals. “Ooh” and “aah” sounds are treated as instrumental in this context. Rap or spoken word tracks are clearly “vocal”. The closer the instrumentalness value is to 1.0, the greater likelihood the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is higher as the value approaches 1.0. The variable liveness is a double that detects the presence of an audience in the recording. Higher liveness values represent an increased probability that the track was performed live. A value above 0.8 provides strong likelihood that the track is live. The variable valence is a double that measures from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry). The variable tempo is a double that represents the overall estimated tempo of a track in beats per minute (BPM). In musical terminology, tempo is the speed or pace of a given piece and derives directly from the average beat duration. The variable duration_ms is a double that shows the duration of the song in milliseconds</p>
<ul>
<li><p>Question 1: How does energy compare to the duration of a song? To test this I will create a chart, possibly a point or violin, to show dispersion and look for clustering at certain energy levels and times to see if there is a trend for how long high energy songs typically are and how long low energy songs are.</p></li>
<li><p>Question 2: What are the 10 most popular songs? What genres show up more than once? To test this I will need to filter for genre, song name, and popularity and then arrange them in descending order. From there I will get a list of the top 10 popular songs and can see what genres show up more than once.</p></li>
<li><p>Question 3: How does speechiness compare to popularity? Is there a sweetspot? To test this I will need to graph speechiness against popularity and look for a trend, I will likely start with a point graph and change from there if there is a better solution that presents itself.</p></li>
</ul>
</div>
<div id="global-crop-yields" class="section level1">
<h1>Global Crop Yields</h1>
<p>Exploring the Global Crop Yields data</p>
<pre><code>## Observations: 13,075
## Variables: 14
## $ Entity                             &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afg…
## $ Code                               &lt;chr&gt; &quot;AFG&quot;, &quot;AFG&quot;, &quot;AFG&quot;, &quot;AFG&quot;, &quot;AFG&quot;,…
## $ Year                               &lt;dbl&gt; 1961, 1962, 1963, 1964, 1965, 1966…
## $ `Wheat (tonnes per hectare)`       &lt;dbl&gt; 1.0220, 0.9735, 0.8317, 0.9510, 0.…
## $ `Rice (tonnes per hectare)`        &lt;dbl&gt; 1.5190, 1.5190, 1.5190, 1.7273, 1.…
## $ `Maize (tonnes per hectare)`       &lt;dbl&gt; 1.4000, 1.4000, 1.4260, 1.4257, 1.…
## $ `Soybeans (tonnes per hectare)`    &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ `Potatoes (tonnes per hectare)`    &lt;dbl&gt; 8.6667, 7.6667, 8.1333, 8.6000, 8.…
## $ `Beans (tonnes per hectare)`       &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ `Peas (tonnes per hectare)`        &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ `Cassava (tonnes per hectare)`     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ `Barley (tonnes per hectare)`      &lt;dbl&gt; 1.0800, 1.0800, 1.0800, 1.0857, 1.…
## $ `Cocoa beans (tonnes per hectare)` &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA…
## $ `Bananas (tonnes per hectare)`     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA…</code></pre>
<pre><code>## Observations: 11,965
## Variables: 5
## $ Entity                                            &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afg…
## $ Code                                              &lt;chr&gt; &quot;AFG&quot;, &quot;AFG&quot;, &quot;AFG&quot;…
## $ Year                                              &lt;dbl&gt; 1961, 1962, 1963, 1…
## $ `Cereal yield (tonnes per hectare)`               &lt;dbl&gt; 1.1151, 1.0790, 0.9…
## $ `Nitrogen fertilizer use (kilograms per hectare)` &lt;dbl&gt; NA, NA, NA, NA, NA,…</code></pre>
<pre><code>## Observations: 49,403
## Variables: 6
## $ Entity                                                  &lt;chr&gt; &quot;Afghanistan&quot;…
## $ Code                                                    &lt;chr&gt; &quot;AFG&quot;, &quot;AFG&quot;,…
## $ Year                                                    &lt;chr&gt; &quot;1961&quot;, &quot;1962…
## $ `Tractors per 100 sq km arable land`                    &lt;dbl&gt; 0.1568627, 0.…
## $ `Cereal yield (kilograms per hectare) (kg per hectare)` &lt;dbl&gt; 1115.1, 1079.…
## $ `Total population (Gapminder)`                          &lt;dbl&gt; 9169000, 9351…</code></pre>
<pre><code>## Observations: 49,259
## Variables: 6
## $ Entity                                                      &lt;chr&gt; &quot;Afghanis…
## $ Code                                                        &lt;chr&gt; &quot;AFG&quot;, &quot;A…
## $ Year                                                        &lt;chr&gt; &quot;1961&quot;, &quot;…
## $ `Cereal yield index`                                        &lt;dbl&gt; 100, 97, …
## $ `Change to land area used for cereal production since 1961` &lt;dbl&gt; 100, 103,…
## $ `Total population (Gapminder)`                              &lt;dbl&gt; 9169000, …</code></pre>
<pre><code>## Observations: 11,280
## Variables: 4
## $ Entity                                                                   &lt;chr&gt; …
## $ Code                                                                     &lt;chr&gt; …
## $ Year                                                                     &lt;dbl&gt; …
## $ `Arable land needed to produce a fixed quantity of crops ((1.0 = 1961))` &lt;dbl&gt; …</code></pre>
<p>For this project I am examining the Global Crop Yields dataset contained in 5 different csv files on the Tidy Tuesday website. The definitions for each variable were taken from the <a href="https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-21/readme.md">Tidy Tuesday Global Crop Yields website</a>. All 5 datasets have the variables Entity(character, Country or Region Name), Code (character, Country Code (note is NA for regions/continents)), and Year(double, Year). key_crop_yields(13,075 observation with 14 variables) holds the variables Wheat (tonnes per hectare) (double, Wheat yield), Rice (tonnes per hectare) (double, Rice Yield), Maize (tonnes per hectare) (double, Maize yield), Soybeans (tonnes per hectare) (double, Soybeans yield), Potatoes (tonnes per hectare) (double, Potato yield), Beans (tonnes per hectare) (double, Beans yield), Peas (tonnes per hectare) (double, Peas yield), Cassava (tonnes per hectare) (double, Cassava (yuca) yield), Barley (tonnes per hectare) (double, Barley yield), Cocoa beans (tonnes per hectare) (double, Cocoa beans yield), and Bananas (tonnes per hectare) (double, Bananas) all in tonnes per hectare. arable_land(11,280 observations with 4 variables) holds the variable Arable land needed to produce a fixed quantity of crops ((1.0 = 1961)) which is a double that shows the arable land needed to produce a fixed quantity of crops with arable land normalized to 1961. fertilizer(11,965 observations with 5 variables) contains the variables Cereal yield (tonnes per hectare) which is a double that shows the cereal yield in tonnes per hectare and Nitrogen fertilizer use (kilograms per hectare) which is a double that shows the Nitrogen fertilizer use kg per hectare. land_use(49,259 observations with 6 variables) contains the variables cereal yield index(double, cereal yield index), change to land area used for cereal production since 1961(double, change to land area use for cereal production relative since 1961), and total population (gapminder)(double, total population from gapminder data). tractors(49,403 observations with 6 variables) contains the variables Tractors per 100 sq km arable land(double, number of tractors per 100 sq km of arable land), Cereal yield (kilograms per hectare) (kg per hectare) which is a double showing the cereal yield in kg per hectare, and Total population (Gapminder)(double, total population from gapminder).</p>
<ul>
<li><p>Question 1: How does Tractors per 100 sq km arable land affect Total population over time in Ireland? Is there a clear trend that the number tractors affect population growth? To test this I will need to use the tractors dataset, filter for the years 1961-2005 since those are the years with available data, and I can go about answering the question in two ways. I can either make two line graphs with time as a variable or just one comparing the two variables against eachother. The two variables are Tractors per 100 sq km arable land and Total population (Gapminder). I will need to look at when the Tractors ratio is increasing if the population increases at a faster rate.</p></li>
<li><p>Question 2: How has the output of potatoes been affected in Ireland from 1961 to 2018? What years had the highest and lowest potato production? To test this I need to use the key_crop_yields dataset and select Ireland as the country and the years past 1961. Then I need to graph the output of potatoes vs time in years as a line graph. From there I can either see what years had the highest or lowest from the graph or use max/min functions in the piping or arrange in ascending and descending order.</p></li>
<li><p>Question 3: How efficient has Ireland become with producing crops on arable land since 1961? To test this I will need to use the arable_land dataset and use the Arable land needed to produce a fixed quantity of crops ((1.0 = 1961)). I will have to filter for the years between 1961 and 2005 since those are the years where data is recorded for this variable. Then I will need to make a line graph of the variable previously noted over those years and look for any trends.</p></li>
</ul>
</div>
